version: "3.9"

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REQUEST_ORIGIN: http://localhost:5000

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_BACKEND_URL_ARG: http://host.docker.internal:8080
    ports:
      - "5000:5000"
    depends_on:
      - backend
